language: go
go:
- 1.9
sudo: required
addons:
  apt:
    packages:
    - upx-ucl
    - musl
env:
  global:
  - MAKEFLAGS="-j 4"
  - COMMIT=${TRAVIS_COMMIT::8}
  - DOCKER_USERNAME=cblomart
  - secure: "k3+gq0R5uBZpG79sMHb/wjgoy9b3Lknq0uhG1MZwqA7bFB2n2vk5vQwk7c5knOGonULfL8qLyIpOuhNdmRpB9VdzpvFH2bnaFqxeC5G7jU+FxsBypsUYcJSmfxW2EBf4qGc/LemhzRl9C1jc6O07MDV+er063Nsbp/f942Oura64bGABi+lJjN7OLoJKZy3bY7e2jdxSbkIkrrYMrow83ZPfBqqt8hehX80r87VpBNBSS2ZDBEhuMkP2c5z5XozbgG17XoyR5Oway6slg5YxMrDNvwNxNNMLGk51U+Z2+Ov/dwOa5DpoDux/h03hubILozi2t/yBI0Syd9MD0o1EhKlIMBP1EikqsghbHDwDO0m7LIjWB59CMC10KTwDqbat2V1XvLBIwFvBqqWqtb9HDHJHNhVQfrpa0s4diEfBEL9vr2K8ACo81xZUgBty6g5Chw25qrRJwSfentvSNJHZwlCGBQn1IC55J8c/D+a9TpVgaRB0V7hHZf2P2xtWdXkdVaGl3yKYF0sc6RIWY5SC8uyKXDxWjUxBhxy6ToaixdF63ToZMkaJIGoibfLf8XDESOMbHMosGF3Dn8D8jPuIakdEzuEI5sH5GgPh10AbedYDfk29jt5icCRUvvZ2HyLc4L2sc2bDqntr87wQg4eOz9LH2fla53erLpyQPT4kaAs="
matrix:
  - BUILD_JOB=windows-amd64
  - BUILD_JOB=darwin-amd64
  - BUILD_JOB=linux-amd64
  - BUILD_JOB=linux-arm
services:
- docker
before_cache:
- rm -rf $GOPATH/src/github.com/cblomart/spliceproxy
- rm -rf $GOPATH/pkg/**/github.com/cblomart/spliceproxy
cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg
install:
- make deps
- make checks
script:
- make dist-$BUILD_JOB
- make docker-$BUILD_JOB
before_deploy:
- for file in $(ls /tmp/*.tgz); do name=$(echo $file | sed s/\.tgz//g); mv $file ${name}_${TRAVIS_TAG}.tgz; done;
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "fuwECa91wDX3L5mGglRT1zIm60n7ZrJ8OU5EvLmFETUUg/6h9cPG4oVNTylVNYjWZH6S9beMVvXDIP11Jpnm9lZY8Ge3WRHaJmXgk7flpavL5Un6SST+9yfN8OYOXJc6MYYm5ah9pBD7UnJuL1GkNfNbJ2W9w30Ot1kYY6jsyvILy0DRCUzO6zQzNNOS5g+32jB5sxCdRup0GQrMT9mXVFYls9//EZGZOQHQr4CP6OvvHHrjWJlowuAFa/nLfbTMwtLzZJORIJe0Y+cr6O0Z9bJpHcL7RaQujqO7CVCPjXBdd+smRv5c58nFlobqEg2bjU0oifKI6nt+VHRVDXxvO6osy5n1zhah/pDrmXV737tzL1JO6pkKcLed8I0gsVznrVmlLISeHGYhncSVHY/PX3S2Rg/kK4pjGAFcwOVHQNYkDcuBBwkYIukw5tmoJ3Ow9uviwNdQxSnnP8MvfQ9UunM/ca4rVfD3ER1nLqvmpmCQaqczUDMMTwNm5Z61siZvi5skp4RSqdisoY/ep3vYNf7uLh0c3go/SSwqLEWWtSn+kNov9AalGt2JU28sXN0MDkagRai3dVQbnm+SRhAHEgjnWroV9VDdg1VgLCjV0injxmdqF9XLNwjEIcmIpWJ9ZXAVBfBvSsdb/4ZCMWPaVrob1DUxZqE8xrFQwctbKwo="
  file_glob: true
  file: /tmp/spliceproxy_*.tgz  
  on:
    tags: true
after_success:
- if [ "$BUILD_JOB" == "linux-amd64" ]; then DNAME="spliceproxy"; elif [ "$BUILD_JOB" == "linux-arm" ]; then DNAME="rpi-spliceproxy"; fi
- if [ "$TRAVIS_TAG" == "" -a "$TRAVIS_BRANCH" == "master" -a "$DNAME" != "" ]; then docker tag $DOCKER_USERNAME/$DNAME $DOCKER_USERNAME/$DNAME:$COMMIT; fi
- if [ "$TRAVIS_TAG" != "" -a "$DNAME" != "" ]; then docker tag $DOCKER_USERNAME/$DNAME $DOCKER_USERNAME/$DNAME:$TRAVIS_TAG; docker tag $DOCKER_USERNAME/$DNAME $DOCKER_USERNAME/$DNAME:latest; fi
- if [ "$DNAME" != "" ]; then docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD; fi
- if [ "$TRAVIS_TAG" == "" -a "$TRAVIS_BRANCH" == "master" -a "$DNAME" != "" ]; then docker push $DOCKER_USERNAME/$DNAME:$COMMIT; fi
- if [ "$TRAVIS_TAG" != "" -a "$DNAME" != "" ]; then docker push $DOCKER_USERNAME/$DNAME:$TRAVIS_TAG; docker push $DOCKER_USERNAME/$DNAME:latest; fi
