timeout: 10

buffer: 1024

catchall: 
    http: 127.0.0.1:8080
    https: 127.0.0.1:8443

listen:
    https: 
        - 0.0.0.0:443
    http: 
        - 0.0.0.0:80

alloweddomains:
    - name: example.com
    - name: github.com

check: 30
